In [1]:
import numpy as np


In [2]:
1 + 1

2

In [3]:
2 + 3

5

In [4]:
9 + 9

18

In [5]:
lst= [1,2,3,4]
np.array(lst)

array([1, 2, 3, 4])

In [6]:
lst=[1,2,3,4]
arr=np.array(lst)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(4,)

In [9]:
arr1=np.array([[1,2,3],[4,5,6]])

In [10]:
arr1.shape

(2, 3)

In [11]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [13]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
np.array((1,2,34))

array([ 1,  2, 34])

In [15]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr1.dtype



dtype('int32')

In [17]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [18]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [19]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [21]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [22]:
## 40 element from 1 to 50 
np.linspace(1,50,40)

array([ 1.        ,  2.25641026,  3.51282051,  4.76923077,  6.02564103,
        7.28205128,  8.53846154,  9.79487179, 11.05128205, 12.30769231,
       13.56410256, 14.82051282, 16.07692308, 17.33333333, 18.58974359,
       19.84615385, 21.1025641 , 22.35897436, 23.61538462, 24.87179487,
       26.12820513, 27.38461538, 28.64102564, 29.8974359 , 31.15384615,
       32.41025641, 33.66666667, 34.92307692, 36.17948718, 37.43589744,
       38.69230769, 39.94871795, 41.20512821, 42.46153846, 43.71794872,
       44.97435897, 46.23076923, 47.48717949, 48.74358974, 50.        ])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros(10).reshape(5,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [28]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [30]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [31]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [32]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Generating random number

In [34]:
print("Random number generation(Uniform distribution)")
np.random.rand(2,3)

Random number generation(Uniform distribution)


array([[0.402481  , 0.94395606, 0.2840985 ],
       [0.31067744, 0.69738839, 0.95207223]])

In [35]:
print("Random number following a normal distribution with mean=0 and std=1")
print(np.random.randn(5,3))

Random number following a normal distribution with mean=0 and std=1
[[-0.82797616  0.80765504 -0.58246347]
 [ 0.79517385  0.8102986  -0.7122466 ]
 [ 0.33537058 -0.50858015 -0.29262313]
 [ 2.0049108   0.62257988  0.41851606]
 [ 0.52780192  0.2681845   2.05847755]]


In [36]:
np.random.randint(1,100,50)

array([23, 47, 54, 70, 34, 44, 54, 23, 96, 70, 19, 22, 75, 26, 96, 90, 64,
       43, 19, 89, 66, 64, 97, 83, 42, 29, 90, 86, 62,  1, 90, 21, 71, 77,
       97, 69, 14, 14, 52, 82, 26, 89, 43, 32, 17,  3, 10, 31,  2, 54])

In [37]:
np.random.randint(1,100,(4,4))

array([[ 5, 89, 55, 48],
       [11, 43,  9, 26],
       [ 3, 15, 90, 71],
       [17, 34, 20,  1]])

In [38]:
arr=np.arange(0,11)

# Slicing

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [41]:
arr[-1:7]

array([], dtype=int32)

In [42]:
arr[-1:7:-1]

array([10,  9,  8])

In [43]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [44]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [45]:
arr1

array([[38, 33, 17, 95],
       [30, 42, 25, 52],
       [79, 91, 73,  6],
       [51, 82, 46, 46],
       [59, 61, 56, 75]])

In [46]:
arr1[0:3,0:3]

array([[38, 33, 17],
       [30, 42, 25],
       [79, 91, 73]])

In [47]:
arr1[3:]

array([[51, 82, 46, 46],
       [59, 61, 56, 75]])

In [48]:
arr1[3:,1:]

array([[82, 46, 46],
       [61, 56, 75]])

In [49]:
arr1[0:3,0:3]

array([[38, 33, 17],
       [30, 42, 25],
       [79, 91, 73]])

In [50]:
arr1

array([[38, 33, 17, 95],
       [30, 42, 25, 52],
       [79, 91, 73,  6],
       [51, 82, 46, 46],
       [59, 61, 56, 75]])

In [51]:
arr1[2:4,1:3]

array([[91, 73],
       [82, 46]])

In [52]:
arr1[-3:-1,-3:-1]

array([[91, 73],
       [82, 46]])

universal functions

In [53]:
arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [54]:
arr1

array([[17, 62, 76],
       [41, 19, 48],
       [15, 48, 71]])

In [55]:
arr2

array([[73, 88, 64],
       [65, 36, 33],
       [98, 51, 59]])

In [56]:
arr1 + arr2

array([[ 90, 150, 140],
       [106,  55,  81],
       [113,  99, 130]])

In [57]:
arr1 * arr2

array([[1241, 5456, 4864],
       [2665,  684, 1584],
       [1470, 2448, 4189]])

In [58]:
arr1 / arr2

array([[0.23287671, 0.70454545, 1.1875    ],
       [0.63076923, 0.52777778, 1.45454545],
       [0.15306122, 0.94117647, 1.20338983]])

In [59]:
np.sqrt(arr1)

array([[4.12310563, 7.87400787, 8.71779789],
       [6.40312424, 4.35889894, 6.92820323],
       [3.87298335, 6.92820323, 8.42614977]])

In [60]:
np.sqrt(arr2)

array([[8.54400375, 9.38083152, 8.        ],
       [8.06225775, 6.        , 5.74456265],
       [9.89949494, 7.14142843, 7.68114575]])

In [61]:
np.exp(arr2)

array([[5.05239363e+31, 1.65163625e+38, 6.23514908e+27],
       [1.69488924e+28, 4.31123155e+15, 2.14643580e+14],
       [3.63797095e+42, 1.40934908e+22, 4.20121040e+25]])

In [62]:
np.log10(arr1)

array([[1.23044892, 1.79239169, 1.88081359],
       [1.61278386, 1.2787536 , 1.68124124],
       [1.17609126, 1.68124124, 1.85125835]])

In [63]:
np.log10(arr2)

array([[1.86332286, 1.94448267, 1.80617997],
       [1.81291336, 1.5563025 , 1.51851394],
       [1.99122608, 1.70757018, 1.77085201]])

In [64]:
np.log10(arr2)

array([[1.86332286, 1.94448267, 1.80617997],
       [1.81291336, 1.5563025 , 1.51851394],
       [1.99122608, 1.70757018, 1.77085201]])

In [65]:
arr1=np.arange(1,10)

In [66]:
arr1[2:]=1000

In [67]:
arr1[2:]=1000

In [68]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [69]:
arr2

array([[73, 88, 64],
       [65, 36, 33],
       [98, 51, 59]])

In [70]:
arr2=np.arange(1,10)

In [71]:
arr2[2:]=3000

In [72]:
arr2

array([   1,    2, 3000, 3000, 3000, 3000, 3000, 3000, 3000])

In [73]:
np.dot(arr1,arr2)

21000005

In [74]:
np.matmul(arr1,arr2)

21000005