In [4]:
import numpy as np


In [5]:
1 + 1

2

In [6]:
2 + 3

5

In [7]:
9 + 9

18

In [8]:
lst= [1,2,3,4]
np.array(lst)

array([1, 2, 3, 4])

In [9]:
lst=[1,2,3,4]
arr=np.array(lst)

In [10]:
type(arr)

numpy.ndarray

In [12]:
arr.shape

(4,)

In [13]:
arr1=np.array([[1,2,3],[4,5,6]])

In [14]:
arr1.shape

(2, 3)

In [15]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [17]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])